replicaCount: 1
image:
  repository: gcr.io/ajensen-1993/ajensen-server
  pullPolicy: IfNotPresent
  tag: ""
  digest: ""
env: []
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
priorityClassName: normal-nonpreempting-pc
serviceAccount: {}
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  name: http
  port: 80
  containerPort: 80
  protocol: TCP
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      preference:
        matchExpressions:
        - key: cloud.google.com/gke-preemptible
          operator: Exists